# Generated by Django 3.2.3 on 2021-07-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
